### PR TITLE
Fixes misplaced LLAMA_NO_HOST_ACC_WARNING.

### PR DESCRIPTION
**Pull request by tdd11235813**

### CODE REVIEW

**Comment by bertwesarg** [comment]
+1

**Comment by theZiz** [comment]
How did you find this? This never throw an error for me. :open_mouth:

**Comment by bertwesarg** [comment]
I think it was `nvcc` from CUDA 10,which started to trigger this.

**Comment by theZiz** [comment]
Wow, *some* bugs they're fixing! :stuck_out_tongue:

**Comment by ax3l** [comment]
No, iirc from a similar bug in alpaka, the check just became more strict now.

**Pull request merged**
