### PR TITLE
More tests for tree mappings

### PR DESCRIPTION
**Pull request by bernhardmgruber**
- [x] requires merging #36 

* added deduction guide for `llama::tuple`
* more tests for tree mappings

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
I merged #36

**Comment by psychocoderHPC** [comment]
I will always look only to the ubuntu CI until windows is fixed. This PR broke the ubuntu CI

**Comment by bernhardmgruber** [comment]
It seems like a compiler issue. g++7 fails, but g++9 compiles fine.

**Comment by bernhardmgruber** [comment]
I was wrong, it was not the compiler version. I built in different modes (debug/release). I removed the code differences between debug/release mode.

**Comment by bernhardmgruber** [comment]
Looks good! Please merge ;)

**Pull request merged**
